name: 'Build the solution'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOL_DIR: 'inference/OpenLipSync.Inference/OpenLipSync.Inference'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Restore solution
        run: dotnet restore $SOL_DIR
      - name: Build solution
        run: dotnet build -c Release $SOL_DIR
      - name: Package solution
        run: dotnet pack -c Release $SOL_DIR
      - uses: actions/upload-artifact@v4
        with:
          path: '**/**/*.nupkg'
